import {
  DentalService,
  Clinician,
  Appointment,
  WebInquiry,
  SmileGalleryCase,
  CompanyDetails,
  ClinicPolicies,
  FAQItem,
  AIGuardrails,
  AIProviderSettings,
  AppointmentApprovalPolicy,
} from '@/types/clinic';

export const DEFAULT_SERVICES: DentalService[] = [
  {
    id: 'srv-checkup',
    name: 'Comprehensive Oral Examination & 3D Scan',
    priceRange: 'From £95',
    basePriceGbp: 95,
    depositGbp: 35,
    category: 'General',
    duration: '45 min',
    description: 'Full 14-point oral cancer screen, digital low-dose OPG X-rays, 3D intraoral digital optical scan, and bespoke treatment roadmap.',
    insuranceCoverage: 'Eligible for all UK Private Dental Insurance (Bupa, AXA, Aviva, Denplan)',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Dr. Alistair Vance', 'Dr. Sarah Jenkins', 'Dr. Michael Zhao'],
    features: [
      'Single visit (45 mins)',
      'Low-dose digital OPG panoramic X-rays',
      'iTero 3D digital bite & occlusion scan',
      'Written clinical treatment report & itemised fees',
    ],
    popular: true,
    financeMonthlyFrom: 0,
  },
  {
    id: 'srv-hygiene',
    name: 'Guided Biofilm Therapy & Airflow® Polishing',
    priceRange: 'From £110',
    basePriceGbp: 110,
    depositGbp: 30,
    category: 'General',
    duration: '50 min',
    description: 'Swiss EMS Airflow therapy delivering pain-free warm water spray for stubborn coffee, tea, and tobacco stain removal and deep gum detox.',
    insuranceCoverage: 'Preventive Tier Eligible',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Emma Crawford RDH'],
    features: [
      'Single visit (50 mins)',
      'Swiss EMS Airflow Erythritol polishing',
      'Gentle ultrasonic piezon plaque removal',
      'Fluoride enamel remineralisation treatment',
    ],
    financeMonthlyFrom: 0,
  },
  {
    id: 'srv-invisalign',
    name: 'Invisalign® Clear Aligners & 3D Simulation',
    priceRange: 'From £2,450',
    basePriceGbp: 2450,
    depositGbp: 250,
    category: 'Cosmetic',
    duration: '3 to 9 months',
    description: 'Discreet, removable custom clear aligners with complimentary iTero® 3D digital smile simulation showing your final result before starting.',
    insuranceCoverage: 'Orthodontic Tier & HSA Eligible',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. Sarah Jenkins', 'Dr. Alistair Vance'],
    features: [
      '2-4 clinical check-in visits',
      'Free iTero® 3D Outcome Simulator',
      'Complimentary teeth whitening at finish (worth £395)',
      '3 sets of Vivera® retainers included',
    ],
    financeMonthlyFrom: 102,
  },
  {
    id: 'srv-implants',
    name: 'Precision Straumann® Titanium Dental Implant',
    priceRange: 'From £1,650',
    basePriceGbp: 1650,
    depositGbp: 200,
    category: 'General',
    duration: '3 months',
    description: 'Permanent tooth replacement using world-leading Swiss Straumann® implants and custom color-matched zirconia crown crafted in our in-house lab.',
    insuranceCoverage: 'Implant Tier Co-Pay',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. Alistair Vance'],
    features: [
      '3-4 visits over 12 weeks',
      'High-resolution CBCT 3D bone density scan',
      'Computer-guided keyhole surgical placement',
      'Lifetime manufacturer hardware warranty',
    ],
    financeMonthlyFrom: 68,
  },
  {
    id: 'srv-whitening',
    name: 'Philips Zoom!® In-Chair Laser Whitening',
    priceRange: 'From £395',
    basePriceGbp: 395,
    depositGbp: 75,
    category: 'Cosmetic',
    duration: '60 min',
    description: 'Clinically proven in-chair LED laser activation lifting your smile up to 8 shades whiter with integrated ACP enamel protection.',
    insuranceCoverage: 'Cosmetic Tier',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Dr. Sarah Jenkins', 'Emma Crawford RDH'],
    features: [
      'Single visit (60 mins)',
      'Up to 8 shades lighter in 1 appointment',
      'Enamel-safe desensitising protocol',
      'Includes custom bespoke home maintenance trays',
    ],
    popular: true,
    financeMonthlyFrom: 33,
  },
  {
    id: 'srv-veneers',
    name: 'Bespoke Hand-Layered E.max® Porcelain Veneers',
    priceRange: 'From £795',
    basePriceGbp: 795,
    depositGbp: 150,
    category: 'Cosmetic',
    duration: '2 visits (10 days)',
    description: 'Artisan-crafted ceramic veneers sculpted to harmonise with your facial features, closing gaps and masking deep discolouration permanently.',
    insuranceCoverage: 'Cosmetic Elective Tier',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. Alistair Vance', 'Dr. Sarah Jenkins'],
    features: [
      '2 visits over 7 to 10 days',
      'Digital Smile Design (DSD) trial smile mock-up',
      'Micron-precision preparation preserving tooth structure',
      'Individually hand-glazed by our master ceramist',
    ],
    financeMonthlyFrom: 66,
  },
  {
    id: 'srv-rct',
    name: 'Microscopic Root Canal Therapy (Molar / Premolar)',
    priceRange: 'From £550',
    basePriceGbp: 550,
    depositGbp: 100,
    category: 'General',
    duration: '90 min',
    description: 'Specialist endodontic treatment utilizing German Zeiss surgical dental microscopes to save infected teeth painlessly in a single visit.',
    insuranceCoverage: 'Major Restorative Tier (Up to 80% coverage)',
    requiresPreConsult: true,
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Dr. Michael Zhao'],
    features: [
      'Single visit (90 mins)',
      'Carl Zeiss high-magnification surgical optics',
      'Computerized apex locator and rotary nickel-titanium files',
      'Instant relief from acute throbbing toothache',
    ],
    financeMonthlyFrom: 45,
  },
  {
    id: 'srv-emergency',
    name: '24/7 Same-Day Emergency Dental Triage',
    priceRange: 'From £120',
    basePriceGbp: 120,
    depositGbp: 50,
    category: 'General',
    duration: '30-45 min',
    description: 'Immediate clinical relief for broken crowns, acute abscesses, heavy throbbing pain, facial swelling, or dental sports trauma.',
    insuranceCoverage: 'Emergency Care Full Private Coverage',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. Alistair Vance', 'Dr. Michael Zhao', 'Dr. Sarah Jenkins'],
    features: [
      'Immediate same-day emergency appointment',
      'Diagnostic digital X-ray and immediate pain anaesthesia',
      'Temporary dressing or composite stabilization',
      'Direct clinician hotline & emergency prescription support',
    ],
    financeMonthlyFrom: 0,
  },
];

export const DEFAULT_CLINICIANS: Clinician[] = [
  {
    id: 'clin-alistair-vance',
    name: 'Dr. Alistair Vance',
    title: 'Lead Dental Surgeon & Clinical Director',
    credentials: 'BDS (Hons) Lond, MFDS RCS Eng, M.Sc Oral Implantology',
    gdcNumber: 'GDC No: 248912',
    bio: 'With over 16 years of clinical excellence in Marylebone and Harley Street private practices, Dr. Vance is a recognized specialist in computer-guided implantology, full-mouth oral rehabilitations, and CAD/CAM ceramic aesthetics.',
    experienceYears: 16,
    specialties: ['Dental Implantology', 'Full-Mouth Rehabilitation', 'Digital Smile Design', 'Same-Day CEREC Crowns'],
    photo: '/images/lead-clinician.jpg',
    rating: 4.98,
    reviewsCount: 384,
    verifiedProcedures: 4200,
  },
  {
    id: 'clin-sarah-jenkins',
    name: 'Dr. Sarah Jenkins',
    title: 'Specialist Cosmetic Dentist & Invisalign Platinum',
    credentials: 'BDS (KCL), MJDF RCS Eng, PG Cert Aesthetic Dentistry',
    gdcNumber: 'GDC No: 271890',
    bio: 'Graduating with honours from King’s College London, Dr. Jenkins focuses exclusively on minimally invasive cosmetic dentistry, composite edge bonding, bespoke E.max porcelain veneers, and comprehensive clear aligner therapy.',
    experienceYears: 11,
    specialties: ['Invisalign® Platinum Elite', 'Hand-Layered Porcelain Veneers', 'Composite Bonding', 'Smile Makeovers'],
    photo: '/images/dr-sarah-jenkins.jpg',
    rating: 4.96,
    reviewsCount: 290,
    verifiedProcedures: 2750,
  },
  {
    id: 'clin-michael-zhao',
    name: 'Dr. Michael Zhao',
    title: 'Endodontist & Microscopic Restorative Surgeon',
    credentials: 'BDS (Bristol), MClinDent Endodontology, MEndo RCS Edin',
    gdcNumber: 'GDC No: 285431',
    bio: 'A member of the Royal College of Surgeons of Edinburgh, Dr. Zhao specializes in microscopic root canal surgery and preserving compromised teeth using 3D surgical microscopes with exceptional precision.',
    experienceYears: 12,
    specialties: ['Microscopic Endodontics', 'Apicoectomy', 'Dental Trauma Management', 'Complex Retreatment'],
    photo: '/images/dr-michael-zhao.jpg',
    rating: 4.94,
    reviewsCount: 215,
    verifiedProcedures: 3100,
  },
  {
    id: 'clin-emma-crawford',
    name: 'Emma Crawford RDH',
    title: 'Senior Dental Hygienist & Prevention Specialist',
    credentials: 'Dip Dent Hygiene (Eng), BSc Oral Health Sciences',
    gdcNumber: 'GDC No: 198422',
    bio: 'Emma is certified in Swiss Guided Biofilm Therapy (GBT) and specializes in patient-centric, gentle dental hygiene care, periodontal stability maintenance, and clinical stain prevention.',
    experienceYears: 9,
    specialties: ['Guided Biofilm Therapy', 'Swiss EMS Airflow®', 'Periodontal Maintenance', 'Enamel Remineralisation'],
    photo: '/images/lead-clinician.jpg',
    rating: 4.97,
    reviewsCount: 180,
    verifiedProcedures: 1900,
  },
];

export const LEAD_CLINICIAN: Clinician = DEFAULT_CLINICIANS[0];

export const DEFAULT_GALLERY_CASES: SmileGalleryCase[] = [
  {
    id: 'case-1',
    title: '8-Unit Anterior E.max® Ceramic Veneers & Edge Rebuilding',
    category: 'Cosmetic',
    beforeImage: '/images/smile-before-1.jpg',
    afterImage: '/images/smile-after-1.jpg',
    procedureNotes: 'Corrected chipped central incisor, severe incisal edge enamel attrition, and longstanding coffee discolouration. Shade lifted from natural A3 to bright BL2 using minimal-prep lithium disilicate veneers.',
    duration: '2 clinical visits (10 days total)',
    clinicianName: 'Dr. Alistair Vance',
    clinicianGdc: 'GDC No: 248912',
    tags: ['Porcelain Veneers', 'Digital Smile Design', 'Chipped Tooth Repair'],
  },
  {
    id: 'case-2',
    title: 'Invisalign® Clear Aligners + Zoom! Laser Whitening',
    category: 'Orthodontics',
    beforeImage: '/images/smile-before-1.jpg',
    afterImage: '/images/smile-after-1.jpg',
    procedureNotes: 'Resolved lower crowding, corrected anterior midline deviation, followed by 60-minute in-chair laser tooth whitening and custom night retention.',
    duration: '5 months (16 aligner stages)',
    clinicianName: 'Dr. Sarah Jenkins',
    clinicianGdc: 'GDC No: 271890',
    tags: ['Invisalign', 'Teeth Whitening', 'Overcrowding'],
  },
  {
    id: 'case-3',
    title: 'Upper Premolar Straumann® Implant & In-House Zirconia Crown',
    category: 'Implants',
    beforeImage: '/images/smile-before-1.jpg',
    afterImage: '/images/smile-after-1.jpg',
    procedureNotes: 'Fractured premolar extracted with immediate titanium implant placement and bone grafting. Final screw-retained ceramic crown milled on our 5-axis CAD/CAM lab.',
    duration: '3 months osseointegration',
    clinicianName: 'Dr. Alistair Vance',
    clinicianGdc: 'GDC No: 248912',
    tags: ['Dental Implant', '5-Axis CAD/CAM', 'Same-Day Crown'],
  },
];

export const DEFAULT_COMPANY_DETAILS: CompanyDetails = {
  clinicName: 'Vertex Dental Lab',
  workingHours: 'Mon - Fri: 08:30 - 18:00 | Sat: 09:00 - 17:00 | Sun: Urgent Care On-Call',
  companyDescription: 'Vertex Dental Lab is an award-winning private dental practice and digital 3D milling laboratory located in Marylebone, London. We combine Harley Street clinical prestige with in-house 5-axis robotic CAD/CAM manufacturing, GDC-registered clinical specialists, and 24/7 AI-assisted patient triage.',
  helplinePhone: '+44 20 7946 0888',
  whatsappPhone: '+44 7700 900888',
  contactEmail: 'reception@vertexdental.co.uk',
  clinicalAddress: '42 Harley Place, Marylebone, London, W1G 9PH, United Kingdom',
  cqcRegistration: 'CQC Registered Provider (Good/Outstanding Rating)',
  bdaMember: 'British Dental Association (BDA) Good Practice Member',
  cqcProviderId: '1-104928374',
  icoRegistration: 'ICO Reg: ZA892147',
};

export const DEFAULT_POLICIES: ClinicPolicies = {
  refundPolicy: 'Consultation deposits are fully refundable with at least 24 hours notice. For bespoke custom restorations (e.g. milled veneers, implant abutments), balances are refunded pro-rata minus laboratory bespoke milling materials already cast.',
  cancellationPolicy: 'We operate a strict 24-to-48-hour notice cancellation policy to ensure clinical chair time can be offered to urgent patients on our waiting list. Rescheduling within the window carries zero fee.',
  additionalPolicies: [
    'Complimentary initial 3D digital smile simulation included with all Invisalign consultations.',
    'All custom prosthetic restorations manufactured in-house carry a 5-year clinical structural guarantee.',
    '0% APR interest-free healthcare finance available on treatments over £1,000 via Chrysalis Finance UK and Tabeo.',
    '100% Hospital-Grade Class-B vacuum autoclave sterilization protocols between every patient visit.',
    'Strict regulatory compliance with General Dental Council (GDC) and Care Quality Commission (CQC) standards.',
  ],
};

export const DEFAULT_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How does the 0% finance payment plan work?',
    answer: 'We partner with Tabeo and Chrysalis Finance UK to offer 0% APR interest-free financing across 6, 10, 12, or 24 months for treatments over £1,000. You pay a flexible deposit (0% to 50%) and spread the remainder in equal monthly direct debits with zero hidden fees.',
    category: 'Pricing & Finance',
  },
  {
    id: 'faq-2',
    question: 'Are all your dentists registered with the General Dental Council (GDC)?',
    answer: 'Yes, 100%. Every dental surgeon, specialist, and dental hygienist at Vertex Dental Lab is fully registered with the UK General Dental Council (GDC) and holds clinical indemnity. GDC numbers are publicly displayed on each clinician’s profile.',
    category: 'Clinical Standards',
  },
  {
    id: 'faq-3',
    question: 'Can I get same-day emergency appointments for acute toothache?',
    answer: 'Yes. We reserve dedicated emergency triage appointments every single day for acute pain, broken teeth, facial swelling, or trauma. You can dial our emergency hotline (+44 20 7946 0888) or use our fast guest triage modal.',
    category: 'Emergency Care',
  },
  {
    id: 'faq-4',
    question: 'What is the benefit of your in-house 5-axis digital milling lab?',
    answer: 'Most dental clinics send impressions to external overseas labs, taking 2 to 3 weeks. Because our 5-axis German milling machines and 3D printing equipment are on-site in Marylebone, we can mill precision crowns and veneers in hours with micron-level accuracy.',
    category: 'Technology',
  },
  {
    id: 'faq-5',
    question: 'How do I know if I am suitable for Invisalign®?',
    answer: 'During your 45-minute consultation, Dr. Sarah Jenkins performs an iTero 3D optical scan of your teeth. The AI Outcome Simulator renders a 3D video showing your exact smile progression from week 1 to completion before you commit.',
    category: 'Cosmetic',
  },
  {
    id: 'faq-6',
    question: 'Do you accept private dental insurance?',
    answer: 'Yes. As a CQC-registered private clinic, our itemised receipts and treatment plans are accepted by all major UK private health insurers including Bupa Dental, AXA Health, Aviva, WPA, and Denplan.',
    category: 'Insurance',
  },
];

export const DEFAULT_AI_GUARDRAILS: AIGuardrails = {
  identityRole: 'You are the official clinical triage, patient guidance, and booking AI concierge for Vertex Dental Lab in Central London.',
  targetAudience: 'UK private dental patients seeking cosmetic dentistry, dental implants, Invisalign, root canal treatment, and urgent dental care.',
  toneManner: 'Empathetic, reassuring, clinically articulate, professional, and adhering strictly to British English medical standards.',
  responseLength: 'Concise and informative. 2 to 4 sentences or a clearly structured bullet list.',
  businessGoals: 'Provide transparent pricing in GBP (£), explain treatment timelines, encourage booking consultations via the frictionless guest triage, and build confidence in our GDC clinicians.',
  shouldSay: [
    'Strictly quote verified starting fees in GBP (£) as published in the Vertex Dental Lab fee schedule.',
    'Emphasize our in-house 5-axis CAD/CAM lab and GDC registration numbers for all clinicians.',
    'Direct patients reporting acute facial swelling, throbbing pain, or trauma to call the emergency line +44 20 7946 0888 immediately.',
    'Mention 0% APR interest-free finance options via Chrysalis Finance UK and Tabeo.',
  ],
  mustNotSay: [
    'NEVER prescribe antibiotics, painkillers, or specific medication dosages under any circumstance.',
    'NEVER provide a definitive remote medical diagnosis without an in-person GDC clinical examination.',
    'NEVER quote arbitrary or unauthorized discounts not listed in the official price schedule.',
    'NEVER guarantee 100% biological permanence for complex surgical procedures without clinical qualification.',
  ],
  informationUnavailableInstructions: 'When specific clinical details are unavailable, advise the patient that our front desk team will happily answer bespoke questions via WhatsApp (+44 7700 900888) or phone (+44 20 7946 0888).',
  transferToHumanInstructions: 'If the patient reports acute facial swelling, uncontrolled bleeding, or difficulty breathing, immediately provide our emergency triage hotline (+44 20 7946 0888) and direct them to NHS 111 / hospital A&E.',
  languageBehaviorPolicy: 'Default to British English spelling (e.g. colour, paediatric, anaesthesia, programme, centre) and polite London clinic etiquette.',
};

export const DEFAULT_AI_PROVIDER_SETTINGS: AIProviderSettings = {
  activeProvider: 'Gemini',
  geminiApiKey: 'AIzaSyCLIfxp-Demo-GeminiKey-Vertex-2026',
  geminiModel: 'gemini-2.0-flash',
  claudeApiKey: 'sk-ant-api03-claude-demo-key-encrypted',
  claudeModel: 'claude-3-5-sonnet-20241022',
  chatgptApiKey: 'sk-proj-chatgpt-demo-key-encrypted',
  chatgptModel: 'gpt-4o-mini',
};

export const DEFAULT_APPROVAL_POLICY: AppointmentApprovalPolicy = {
  autoApproveEnabled: true,
  approvedCategories: ['General', 'Preventive', 'Cosmetic', 'Pediatric'],
  manualReviewCategories: ['Surgical', 'Endodontics', 'Orthodontics', 'Emergency'],
  adminApprovalDirectives: 'Auto-approve routine checkups, 3D scans, hygiene therapy, and laser whitening. Surgical implant placements, root canals, and emergency slots are held for Dr. Vance’s clinical sign-off.',
  autoConfirmMessage: 'Consultation request automatically approved per Clinic Schedule Quota.',
  manualReviewMessage: 'Consultation request logged as PENDING: held for Dr. Vance’s clinical diary sign-off.',
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientName: 'Charlotte Kensington',
    patientEmail: 'charlotte.k@mayfairlaw.co.uk',
    patientPhone: '+44 7712 345678',
    serviceId: 'srv-invisalign',
    serviceName: 'Invisalign® Clear Aligners & 3D Simulation',
    clinicianName: 'Dr. Sarah Jenkins',
    date: '2026-10-06',
    timeSlot: '10:30 AM',
    status: 'Confirmed',
    notes: 'Interested in digital smile simulation and 12-month 0% payment plan for wedding in summer.',
    createdAt: '2026-10-02T10:15:00Z',
    source: 'Guest Triage Modal',
    approvedByAI: true,
    aiApprovalReason: 'Auto-approved under cosmetic consult quota.',
  },
  {
    id: 'apt-102',
    patientName: 'Oliver Sterling',
    patientEmail: 'oliver.sterling@gmail.com',
    patientPhone: '+44 7823 456789',
    serviceId: 'srv-implants',
    serviceName: 'Precision Straumann® Titanium Dental Implant',
    clinicianName: 'Dr. Alistair Vance',
    date: '2026-10-07',
    timeSlot: '02:00 PM',
    status: 'Confirmed',
    notes: 'Upper right molar restoration consultation and CBCT 3D bone scan.',
    createdAt: '2026-10-01T14:30:00Z',
    source: 'Reception',
    approvedByAI: false,
    aiApprovalReason: 'Implant surgical consultation reviewed and confirmed by clinic director.',
  },
  {
    id: 'apt-103',
    patientName: 'Eleanor Wright',
    patientEmail: 'eleanor.w@chelsea-art.co.uk',
    patientPhone: '+44 7934 567890',
    serviceId: 'srv-hygiene',
    serviceName: 'Guided Biofilm Therapy & Airflow® Polishing',
    clinicianName: 'Emma Crawford RDH',
    date: '2026-10-08',
    timeSlot: '11:15 AM',
    status: 'Confirmed',
    notes: 'Routine 6-month hygiene maintenance before international travel.',
    createdAt: '2026-10-03T08:20:00Z',
    source: 'AI Assistant',
    approvedByAI: true,
    aiApprovalReason: 'Auto-approved by AI Agent per Admin Approval Policy.',
  },
  {
    id: 'apt-104',
    patientName: 'Marcus Bell',
    patientEmail: 'marcus.bell@techfirm.co.uk',
    patientPhone: '+44 7455 678901',
    serviceId: 'srv-emergency',
    serviceName: '24/7 Same-Day Emergency Dental Triage',
    clinicianName: 'Dr. Alistair Vance',
    date: '2026-10-04',
    timeSlot: '04:30 PM',
    status: 'Confirmed',
    isEmergency: true,
    notes: 'Chipped front tooth during squash game, requires urgent composite rebuild.',
    createdAt: '2026-10-04T07:40:00Z',
    source: 'AI Assistant',
    approvedByAI: false,
    aiApprovalReason: 'Held for manual clinician triage, confirmed by duty surgeon.',
  },
];

export const INITIAL_INQUIRIES: WebInquiry[] = [
  {
    id: 'lead-301',
    patientName: 'Dr. Harrison Wells',
    email: 'harrison.wells@ucl.ac.uk',
    phone: '+44 7799 123456',
    serviceInterest: 'Dental Implants',
    treatmentCategory: 'General',
    message: 'Seeking a second opinion on full upper arch restoration. Do you have availability for CBCT scan next Tuesday morning?',
    createdAt: '2026-10-04T08:45:00Z',
    status: 'New Lead',
    source: 'Guest Triage Modal',
    preferredDate: '2026-10-06',
    preferredTime: '10:30 AM',
  },
  {
    id: 'lead-302',
    patientName: 'Fiona MacLeod',
    email: 'fiona.macleod@scotbank.com',
    phone: '+44 7800 234567',
    serviceInterest: 'Invisalign & Whitening',
    treatmentCategory: 'Cosmetic',
    message: 'I have a wedding in 5 months. Is accelerated clear aligner treatment feasible within this window? Looking for 0% finance.',
    createdAt: '2026-10-03T17:10:00Z',
    status: 'Contacted',
    source: 'AI Bot',
    preferredDate: '2026-10-07',
    preferredTime: '02:00 PM',
  },
  {
    id: 'lead-303',
    patientName: 'James Thornton',
    email: 'j.thornton@mayfairpartners.co.uk',
    phone: '+44 7911 345678',
    serviceInterest: 'Laser Teeth Whitening',
    treatmentCategory: 'Cosmetic',
    message: 'Can I combine hygiene therapy and Zoom laser whitening into a single 90-minute Friday afternoon slot?',
    createdAt: '2026-10-02T11:25:00Z',
    status: 'Consultation Booked',
    source: 'Web Form',
    preferredDate: '2026-10-09',
    preferredTime: '03:30 PM',
  },
  {
    id: 'lead-304',
    patientName: 'Zara Al-Mansoor',
    email: 'zara.almansoor@investcorp.com',
    phone: '+44 7955 889900',
    serviceInterest: 'E.max Porcelain Veneers',
    treatmentCategory: 'Cosmetic',
    message: 'Looking to restore 6 upper front teeth before filming an international broadcast in November. Would love to review 3D smile mock-up.',
    createdAt: '2026-10-01T15:40:00Z',
    status: 'Contacted',
    source: 'Guest Triage Modal',
    preferredDate: '2026-10-08',
    preferredTime: '11:45 AM',
  },
  {
    id: 'lead-305',
    patientName: 'Edward Pemberton',
    email: 'edward.p@kensingtonclub.co.uk',
    phone: '+44 7422 113355',
    serviceInterest: 'Routine Checkup & Airflow',
    treatmentCategory: 'General',
    message: 'Relocating to Marylebone, looking for a reliable private dentist for my family of four.',
    createdAt: '2026-09-29T10:00:00Z',
    status: 'Lost / Archived',
    source: 'Web Form',
  },
];
