import {
  DentalService,
  Clinician,
  Appointment,
  WebInquiry,
  CompanyDetails,
  ClinicPolicies,
  FAQItem,
  AIGuardrails,
  AIProviderSettings,
  AppointmentApprovalPolicy,
} from '@/types/clinic';

export const DEFAULT_SERVICES: DentalService[] = [
  {
    id: 'srv-checkup',
    name: 'Comprehensive Oral Examination',
    priceRange: 'From £150',
    basePriceGbp: 150,
    depositGbp: 35,
    category: 'General',
    duration: '45 min',
    description: 'Full mouth periodontal probe, 3D intraoral scan, digital low-dose OPG X-rays, and comprehensive treatment planning.',
    insuranceCoverage: 'Full Insurance Coverage Eligible',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Dr. S. Jenkins', 'Dr. M. Zhao', 'Hygienist Pool'],
    features: [
      'Comprehensive 14-point oral assessment',
      'Low-radiation digital OPG X-rays',
      'Oral cancer & soft tissue screening',
      'Bespoke digital treatment plan',
    ],
    popular: true,
  },
  {
    id: 'srv-whitening',
    name: 'Laser Teeth Whitening (Zoom)',
    priceRange: 'From £420',
    basePriceGbp: 420,
    depositGbp: 100,
    category: 'Cosmetic',
    duration: '60 min',
    description: 'Philips Zoom in-office LED activation delivering up to 8 shades whiter with enamel-safe desensitizing gel.',
    insuranceCoverage: 'Cosmetic Tier',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. S. Jenkins', 'Hygienist Pool'],
    features: [
      'Philips Zoom! WhiteSpeed laser',
      'Up to 8 shades lighter in 60 mins',
      'Enamel-safe desensitizing gel',
      'Complimentary top-up home trays',
    ],
  },
  {
    id: 'srv-rct',
    name: 'Root Canal Therapy (Molar)',
    priceRange: 'From £850',
    basePriceGbp: 850,
    depositGbp: 200,
    category: 'Endodontics',
    duration: '90 min',
    description: 'Endodontic rotary canal shaping utilizing surgical Zeiss microscope and computerized apex localization.',
    insuranceCoverage: 'Major Medical Copay',
    requiresPreConsult: true,
    onlineBookable: false,
    botRecommended: true,
    assignedProviders: ['Dr. S. Jenkins', 'Dr. M. Zhao'],
    features: [
      'Zeiss surgical dental microscope',
      'Single-visit painless protocol',
      'Digital 3D canal mapping',
      'Immediate acute pain relief',
    ],
  },
  {
    id: 'srv-implants',
    name: 'Dental Implant & Porcelain Crown',
    priceRange: 'From £1,250',
    basePriceGbp: 1250,
    depositGbp: 150,
    category: 'Surgical',
    duration: '60 min',
    description: 'Full titanium post installation with custom color-matched porcelain crown crafted in our in-house milling lab.',
    insuranceCoverage: 'Implant Tier',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Dr. S. Jenkins', 'Dr. M. Zhao'],
    features: [
      'Straumann® premium Swiss implants',
      'CBCT bone density scan included',
      'Custom CAD/CAM in-house crown',
      'Lifetime manufacturer warranty',
    ],
    popular: true,
  },
  {
    id: 'srv-invisalign',
    name: 'Invisalign® & Clear Aligners',
    priceRange: 'From £1,800',
    basePriceGbp: 1800,
    depositGbp: 300,
    category: 'Orthodontics',
    duration: '45 min',
    description: 'Discreet custom-milled orthodontic aligners with complimentary iTero® 3D digital smile simulation.',
    insuranceCoverage: 'Orthodontic Tier',
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. A. Vance'],
    features: [
      'Free iTero® 3D Smile Simulator',
      'Includes retainers & whitening kit',
      '0% finance over 12-24 months',
      'GDC Specialist Orthodontic oversight',
    ],
  },
  {
    id: 'srv-hygiene',
    name: 'Hygiene Therapy & Airflow Polishing',
    priceRange: 'From £110',
    basePriceGbp: 110,
    depositGbp: 30,
    category: 'Preventive',
    duration: '50 min',
    description: 'Advanced ultrasonic scaling combined with Swiss EMS Airflow polishing for deep plaque and stain removal.',
    insuranceCoverage: 'Preventive Tier',
    onlineBookable: true,
    botRecommended: true,
    assignedProviders: ['Hygienist Pool'],
    features: [
      'Swiss EMS Airflow technology',
      'Removes tea, coffee & smoke stains',
      'Ultrasonic gentle calculus removal',
      'Fluoride enamel mineralization',
    ],
  },
  {
    id: 'srv-emergency',
    name: '24/7 Emergency Dental Care',
    priceRange: 'From £120',
    basePriceGbp: 120,
    depositGbp: 50,
    category: 'Emergency',
    duration: '30 min',
    description: 'Immediate clinical relief for acute dental abscesses, fractured crowns, trauma, and acute toothache.',
    insuranceCoverage: 'Emergency Relief',
    requiresPreConsult: true,
    onlineBookable: true,
    botRecommended: true,
    popular: true,
    assignedProviders: ['Dr. S. Jenkins', 'Dr. A. Vance', 'Dr. M. Zhao'],
    features: [
      'Guaranteed same-day triage',
      'Digital pain relief local anaesthesia',
      'Direct clinician hotline & WhatsApp',
      'Open 7 days for urgent care',
    ],
  },
  {
    id: 'srv-pediatric',
    name: 'Pediatric & Family Dentistry',
    priceRange: 'From £75',
    basePriceGbp: 75,
    depositGbp: 20,
    category: 'Pediatric',
    duration: '30 min',
    description: 'Gentle, anxiety-free dental visits for children with protective fissure sealants and positive oral health habits.',
    insuranceCoverage: 'Pediatric Tier',
    onlineBookable: true,
    botRecommended: false,
    assignedProviders: ['Dr. Emily Li'],
    features: [
      'Anxiety-free friendly atmosphere',
      'Protective pit & fissure sealants',
      'Preventive fluoride applications',
      'Fun educational oral hygiene tips',
    ],
  },
];

export const LEAD_CLINICIAN: Clinician = {
  id: 'clin-alistair-vance',
  name: 'Dr. Alistair Vance',
  title: 'Lead Dental Surgeon & Clinical Director',
  credentials: 'BDS (Hons), MFDS RCS Eng, M.Sc Oral Implantology',
  gdcNumber: 'GDC No. 248912',
  bio: 'With over 16 years of clinical excellence in London and Harley Street private practices, Dr. Vance specializes in complex dental implantology, minimally invasive restorative dentistry, and digital CAD/CAM aesthetics.',
  experienceYears: 16,
  specialties: ['Dental Implantology', 'Full Mouth Rehabilitation', 'Digital Smile Design', 'Same-Day CEREC Crowns'],
  photo: '/images/lead-clinician.jpg',
  rating: 4.96,
  reviewsCount: 384,
  verifiedProcedures: 4200,
};

export const DEFAULT_COMPANY_DETAILS: CompanyDetails = {
  clinicName: 'Vertex Dental Lab',
  workingHours: 'Monday to Saturday: 09:00 AM - 06:00 PM, Sunday: Emergency triage only',
  companyDescription: 'Vertex Dental Lab is a premier London private dental clinic and digital laboratory providing world-class bespoke restorative, aesthetic, and surgical dentistry. By fusing in-house robotic CAD/CAM milling with GDC-registered clinical expertise and 24/7 AI-driven patient triage, we ensure every treatment is painless, precise, and comfortable.',
  helplinePhone: '+44 20 7946 0888',
  whatsappPhone: '+44 7700 900888',
  contactEmail: 'info@vertexdentallab.co.uk',
  clinicalAddress: '42 Harley Place, Marylebone, London, W1G 9PH, United Kingdom',
  cqcRegistration: 'CQC Provider ID: 1-104928374 / Compliant',
  bdaMember: 'British Dental Association (BDA) Good Practice Member',
};

export const DEFAULT_POLICIES: ClinicPolicies = {
  refundPolicy: 'Deposit refund processing is carried out within 3 to 5 business days for cancellations adhering to the standard notice window. Treatment course balances may be refunded pro-rata, less direct clinical laboratory custom manufacturing and consumable costs already incurred.',
  cancellationPolicy: 'Vertex Dental Lab requires a minimum of 24 to 48 hours notice to reschedule or cancel appointments without incurring a late cancellation or missed clinical slot fee (£50 for general consultations, £150 for advanced surgical or IV sedation sessions).',
  additionalPolicies: [
    'Please arrive 10 minutes prior to your scheduled appointment for digital medical history verification.',
    '100% Hospital-Grade Class-B vacuum autoclave sterilization protocols applied between every single patient.',
    'Strict adherence to General Dental Council (GDC) and Care Quality Commission (CQC) regulatory standards.',
    '0% APR healthcare financing available on treatments over £1,000 through Chrysalis Finance UK.',
    'All custom prosthetic restorations manufactured in-house carry a 5-year clinical structural guarantee.',
  ],
};

export const DEFAULT_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'Are emergency dental appointments available?',
    answer: 'Yes. We keep dedicated daily emergency slots for acute toothache, broken teeth, facial swelling, or dental trauma. You can call our emergency line (+44 20 7946 0888) or book directly through our 24/7 AI booking assistant.',
    category: 'Emergency',
  },
  {
    id: 'faq-2',
    question: 'What finance options does Vertex Dental Lab offer?',
    answer: 'We provide 0% APR interest-free finance over 6, 10, 12, and 24 months via Chrysalis Finance UK for treatments above £1,000, allowing you to spread the cost comfortably.',
    category: 'Pricing',
  },
  {
    id: 'faq-3',
    question: 'How does the in-house Vertex Dental Lab benefit my treatment?',
    answer: 'Because our advanced CAD/CAM milling machines and 3D printing lab are on-site, we can manufacture precision crowns, bridges, and implant prosthetics on the same day—eliminating weeks of waiting and uncomfortable temporary fittings.',
    category: 'Technology',
  },
  {
    id: 'faq-4',
    question: 'Is dental implant surgery painful?',
    answer: 'No. The procedure is performed under computerized local anaesthesia (The Wand®) with optional IV twilight sedation. Most patients report feeling minimal pressure during the procedure and easily manageable mild tenderness the next day.',
    category: 'Surgical',
  },
  {
    id: 'faq-5',
    question: 'How long does Invisalign® treatment usually take?',
    answer: 'Treatment times vary between 3 to 12 months depending on the complexity of your alignment. During your free iTero® 3D consultation, you will see a digital 3D model of your teeth moving into place along with an exact timeline.',
    category: 'Cosmetic',
  },
  {
    id: 'faq-6',
    question: 'Do you accept NHS patients or are you strictly private?',
    answer: 'Vertex Dental Lab is an independent private clinical practice and dental laboratory. This independence allows us to spend longer appointment times with each patient, utilize state-of-the-art Swiss equipment, and guarantee zero waiting lists.',
    category: 'General',
  },
];

export const DEFAULT_AI_GUARDRAILS: AIGuardrails = {
  identityRole: 'You are the official, intelligent triage, reasoning, and booking AI assistant for Vertex Dental Lab clinic in London, United Kingdom.',
  targetAudience: 'Private dental patients in the UK seeking consultations, cosmetic dentistry, dental implants, teeth whitening, hygiene, and emergency dental care.',
  toneManner: 'Empathetic, professional, polite, clinically reassuring, trustworthy, and British English phrased.',
  responseLength: 'Concise and helpful. 2 to 4 sentences or a clean bullet list.',
  businessGoals: 'Provide accurate clinic information, reason through patient concerns, apply admin-approved appointment guidelines, and build trust in Vertex Dental Lab.',
  shouldSay: [
    'Strictly quote verified pricing in GBP (£) as set in the official Vertex Dental Lab price schedule.',
    'Emphasize GDC compliance, CQC standards, and British clinical excellence.',
    'Direct patients experiencing acute pain, swelling, or trauma to immediately call the emergency line +44 20 7946 0888.',
    'Encourage booking a comprehensive consultation for personalised clinical assessment.',
    'Highlight in-house CAD/CAM lab precision and same-day dental possibilities.',
  ],
  mustNotSay: [
    'NEVER prescribe medication, dosage amounts, or specific antibiotic courses.',
    'NEVER provide definitive remote medical diagnoses without an in-person GDC clinical examination.',
    'NEVER invent unlisted discounts, unofficial promo codes, or non-approved pricing.',
    'NEVER guarantee 100% biological permanence for complex surgical procedures without clinical qualification.',
    'NEVER advise a patient to delay urgent hospital care if presenting airway compromise or heavy haemorrhaging.',
  ],
  informationUnavailableInstructions: 'When specific clinical details or unusual requests are unavailable, politely advise the patient that our patient care coordinators can assist directly via WhatsApp (+44 7700 900888) or phone (+44 20 7946 0888).',
  transferToHumanInstructions: 'If the patient mentions severe facial swelling, uncontrolled oral bleeding, airway difficulty, or dental avulsion (knocked-out tooth), immediately provide the emergency hotline +44 20 7946 0888, WhatsApp triage button, and NHS 111 / A&E guidance.',
  languageBehaviorPolicy: 'Default to professional British English (e.g. colour, programme, anaesthesia, paediatric), maintaining clear, polite, and reassuring phrasing.',
};

// Exactly 3 Agent API Options: Gemini, Claude, ChatGPT
export const DEFAULT_AI_PROVIDER_SETTINGS: AIProviderSettings = {
  activeProvider: 'Gemini',
  geminiApiKey: 'AIzaSyCLIfxp-Demo-GeminiKey-Vertex-2026',
  geminiModel: 'gemini-2.0-flash',
  claudeApiKey: 'sk-ant-api03-claude-demo-key-encrypted',
  claudeModel: 'claude-3-5-sonnet-20241022',
  chatgptApiKey: 'sk-proj-chatgpt-demo-key-encrypted',
  chatgptModel: 'gpt-4o-mini',
};

// Admin Appointment Approval Policy
export const DEFAULT_APPROVAL_POLICY: AppointmentApprovalPolicy = {
  autoApproveEnabled: true,
  approvedCategories: ['General', 'Preventive', 'Cosmetic', 'Pediatric'],
  manualReviewCategories: ['Surgical', 'Endodontics', 'Orthodontics', 'Emergency'],
  adminApprovalDirectives: 'Auto-approve routine checkups, digital OPG scans, Airflow hygiene cleanings, laser whitening, and pediatric visits. For complex procedures (dental implants, root canals, Invisalign, emergencies), flag for Dr. Vance’s manual clinical verification before confirmation.',
  autoConfirmMessage: 'Appointment automatically verified and APPROVED according to clinic schedule directives.',
  manualReviewMessage: 'Appointment logged as PENDING: This procedure requires manual clinical approval by Lead Surgeon Dr. Vance.',
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientName: 'Charlotte Kensington',
    patientEmail: 'patient@vertexdental.co.uk',
    patientPhone: '+44 7712 345678',
    serviceId: 'srv-invisalign',
    serviceName: 'Invisalign® & Clear Aligners',
    clinicianName: 'Dr. Alistair Vance',
    date: '2026-10-02',
    timeSlot: '10:30 AM',
    status: 'Confirmed',
    notes: 'Interested in digital smile simulation and 12-month 0% payment plan.',
    createdAt: '2026-09-30T10:15:00Z',
    source: 'Online Booking',
    approvedByAI: true,
    aiApprovalReason: 'Approved under routine cosmetic consult quota.',
  },
  {
    id: 'apt-102',
    patientName: 'Oliver Sterling',
    patientEmail: 'oliver.sterling@gmail.com',
    patientPhone: '+44 7823 456789',
    serviceId: 'srv-implants',
    serviceName: 'Precision Bio-Compatible Dental Implants',
    clinicianName: 'Dr. Alistair Vance',
    date: '2026-10-02',
    timeSlot: '02:00 PM',
    status: 'Confirmed',
    notes: 'Upper right molar restoration consultation and CBCT scan.',
    createdAt: '2026-09-29T14:30:00Z',
    source: 'Reception',
    approvedByAI: false,
    aiApprovalReason: 'Surgical implant procedure reviewed and confirmed by clinic director.',
  },
  {
    id: 'apt-103',
    patientName: 'Eleanor Wright',
    patientEmail: 'eleanor.w@outlook.com',
    patientPhone: '+44 7934 567890',
    serviceId: 'srv-hygiene',
    serviceName: 'Hygiene Therapy & Airflow Polishing',
    clinicianName: 'Sarah Jenkins, RDH',
    date: '2026-10-03',
    timeSlot: '11:15 AM',
    status: 'Confirmed',
    notes: 'Routine 6-month hygiene maintenance before international travel.',
    createdAt: '2026-10-01T08:20:00Z',
    source: 'AI Assistant',
    approvedByAI: true,
    aiApprovalReason: 'Auto-approved by AI Agent per Admin Approval Policy (Preventive category).',
  },
  {
    id: 'apt-104',
    patientName: 'Marcus Bell',
    patientEmail: 'marcus.bell@techfirm.co.uk',
    patientPhone: '+44 7455 678901',
    serviceId: 'srv-emergency',
    serviceName: '24/7 Emergency Dental Care',
    clinicianName: 'Dr. Alistair Vance',
    date: '2026-10-01',
    timeSlot: '04:30 PM',
    status: 'Confirmed',
    isEmergency: true,
    notes: 'Chipped front tooth during sports, requires urgent composite rebuild.',
    createdAt: '2026-10-01T09:40:00Z',
    source: 'AI Assistant',
    approvedByAI: false,
    aiApprovalReason: 'Held for manual clinician triage, confirmed by duty surgeon.',
  },
];

export const INITIAL_INQUIRIES: WebInquiry[] = [
  {
    id: 'inq-201',
    patientName: 'Dr. Harrison Wells',
    email: 'harrison.wells@ucl.ac.uk',
    phone: '+44 7799 123456',
    serviceInterest: 'Dental Implants',
    message: 'Seeking a second opinion on full upper arch restoration. Do you have availability for CBCT scan next Tuesday morning?',
    createdAt: '2026-10-01T08:45:00Z',
    status: 'New',
  },
  {
    id: 'inq-202',
    patientName: 'Fiona MacLeod',
    email: 'fiona.macleod@scotbank.com',
    phone: '+44 7800 234567',
    serviceInterest: 'Invisalign & Whitening',
    message: 'I have a wedding in 5 months. Is accelerated clear aligner treatment feasible within this window? Looking for finance options too.',
    createdAt: '2026-09-30T17:10:00Z',
    status: 'Contacted',
  },
  {
    id: 'inq-203',
    patientName: 'James Thornton',
    email: 'j.thornton@mayfairpartners.co.uk',
    phone: '+44 7911 345678',
    serviceInterest: 'Laser Teeth Whitening',
    message: 'Can I combine hygiene therapy and Zoom laser whitening into a single 90-minute Friday afternoon slot?',
    createdAt: '2026-09-30T11:25:00Z',
    status: 'Resolved',
  },
];
