/**
 * jobs/daily-summary.ts
 * Sends daily KPI summary email to reception and purges expired GDPR leads.
 */
import { getDb, Collections, saveKpiSnapshot, purgeExpiredLeads } from '../core/firestore.js';
import { sendReceptionEmail } from '../core/messaging.js';
import { clinicConfig } from '../clinic.config.js';
import { logger } from '../core/logger.js';
import type { TaskPayload, Lead, KpiSnapshot } from '../core/types.js';
import { toZonedTime } from 'date-fns-tz';

export async function handleDailySummary(_payload: TaskPayload): Promise<void> {
  const today = toZonedTime(new Date(), clinicConfig.timezone)
    .toISOString()
    .slice(0, 10);

  logger.info({ date: today }, 'Generating daily summary');

  // ── Compute KPIs ──────────────────────────────────────────────────────────
  const db   = getDb();
  const snap = await db
    .collection(Collections.LEADS)
    .where('createdAt', '>=', `${today}T00:00:00.000Z`)
    .where('createdAt', '<=', `${today}T23:59:59.999Z`)
    .get();

  const leads = snap.docs.map((d) => d.data() as Lead);

  const kpi: KpiSnapshot = {
    date:                    today,
    leadsTotal:              leads.length,
    leadsHot:                leads.filter((l) => l.score === 'HOT').length,
    leadsWarm:               leads.filter((l) => l.score === 'WARM').length,
    leadsCold:               leads.filter((l) => l.score === 'COLD').length,
    emergencies:             leads.filter((l) => l.emergency).length,
    depositsIssued:          leads.filter((l) => l.stripeSessionId).length,
    depositsPaid:            leads.filter((l) => l.depositPaidAt).length,
    depositConversionRate:   leads.filter((l) => l.stripeSessionId).length > 0
      ? leads.filter((l) => l.depositPaidAt).length / leads.filter((l) => l.stripeSessionId).length
      : 0,
    confirmed:               leads.filter((l) => l.status === 'CONFIRMED').length,
    attended:                leads.filter((l) => l.status === 'ATTENDED').length,
    noShows:                 leads.filter((l) => l.status === 'NO_SHOW').length,
    noShowRate:              leads.filter((l) => l.status === 'CONFIRMED').length > 0
      ? leads.filter((l) => l.status === 'NO_SHOW').length / leads.filter((l) => ['ATTENDED', 'NO_SHOW'].includes(l.status)).length
      : 0,
    cancelled:               leads.filter((l) => l.status === 'CANCELLED').length,
    completed:               leads.filter((l) => l.status === 'COMPLETED').length,
    reviewsRequested:        leads.filter((l) => l.reviewMessageCount > 0).length,
    reviewLinksClicked:      leads.filter((l) => l.reviewLinkClicked).length,
    remindersSent:           0, // computed from messages_log if needed
  };

  await saveKpiSnapshot(kpi);

  // ── Format summary email ──────────────────────────────────────────────────
  const pct = (n: number, d: number) =>
    d > 0 ? `${Math.round((n / d) * 100)}%` : 'N/A';

  const body = [
    `📊 DAILY SUMMARY — ${today}`,
    ``,
    `📥 NEW LEADS`,
    `   Total:      ${kpi.leadsTotal}`,
    `   🔴 HOT:     ${kpi.leadsHot}`,
    `   🟡 WARM:    ${kpi.leadsWarm}`,
    `   🔵 COLD:    ${kpi.leadsCold}`,
    `   🚨 Emergency: ${kpi.emergencies}`,
    ``,
    `💳 DEPOSITS`,
    `   Issued:     ${kpi.depositsIssued}`,
    `   Paid:       ${kpi.depositsPaid}`,
    `   Conv. rate: ${pct(kpi.depositsPaid, kpi.depositsIssued)}`,
    ``,
    `📅 APPOINTMENTS`,
    `   Confirmed:  ${kpi.confirmed}`,
    `   Attended:   ${kpi.attended}`,
    `   No-shows:   ${kpi.noShows} (${pct(kpi.noShows, kpi.attended + kpi.noShows)})`,
    `   Cancelled:  ${kpi.cancelled}`,
    `   Completed:  ${kpi.completed}`,
    ``,
    `⭐ REVIEWS`,
    `   Requested:  ${kpi.reviewsRequested}`,
    `   Links clicked: ${kpi.reviewLinksClicked}`,
    ``,
    `Generated by ${clinicConfig.name} Automation System`,
  ].join('\n');

  await sendReceptionEmail({
    leadId:   'SYSTEM',
    subject:  `📊 Daily Summary — ${clinicConfig.name} — ${today}`,
    body,
    template: 'DAILY_SUMMARY',
  });

  // ── GDPR: purge expired unconverted leads ─────────────────────────────────
  const purged = await purgeExpiredLeads(clinicConfig.gdpr.retentionMonthsUnconverted);
  if (purged > 0) {
    logger.info({ purged }, 'GDPR: purged expired unconverted leads');
  }

  logger.info({ date: today, kpi }, 'Daily summary sent and KPI saved');
}
